### ISSUE TITLE
Kelmujen kommentointi

### ISSUE THREAD

**Issue by deram** [iskcrew/isk#1]
Kelmuille olisi hyvä toteuttaa kommentointimahdollisuudet, ja jos mahdollista pääsy tuohon osioon olisi hyvä olla vapaampi kuin kumpikaan nykyinen tunnus. ehkä jopa pelkällä basicauthilla ja kommenttiin pitäisi jättää nimimerkki...

Kommentit voisi näkyä jonkun pienen ikonin kautta kaikissa kalvonäkymissä (joissa ne napit kalvokuvan alla) ja ikonissa numero kommenttien määrästä..

**Comment by depili** [comment]
Tikettijärjestelmä hoitaa :)
